version: 2.1

executors:
  builder-java:
    docker:
      - image: java:11-jdk-slim

  builder-docker:
    docker:
      - image: docker:stable

  toolbox:
    docker:
      - image: alpine:latest

jobs:
  build-jar:
    executor: builder-java
    steps:
      - checkout
      - run: ./gradlew build

  build-docker:
    executor: builder-docker
    steps:
      - run: docker build .

  prepare-nais:
    executor: toolbox
    steps:
      - run:
        command: |
          sed -i 's/latest/${VERSION}/' ./nais/base/nais.yaml
          kustomize build ./nais/dev -o ./nais/nais-dev-deploy.yaml &&  cat ./nais/nais-dev-deploy.yaml
          kustomize build ./nais/prod -o ./nais/nais-prod-deploy.yaml &&  cat ./nais/nais-prod-deploy.yaml

  deploy:
    environment:
      FOO: bar
    steps:
      - run: kubectl

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build:
        - requires:
          - build-jar
          - build-docker
          - prepare-nais
      - deploy-preprod:
          requires:
            - build
            - prepare-nais
          filters:
            branches:
              only: master
      - acceptance-test-uat:
        - requires:
            - deploy-preprod
      - acceptance-test-integration:
        - requires:
            - deploy-preprod
      - acceptance-test-benchmark:
        - requires:
            - deploy-preprod
      - deploy:
          requires:
            - prepare-nais
            - acceptance-test-uat
            - acceptance-test-integration
            - acceptance-test-benchmark
          filters:
            branches:
              only: master
