version: 2.1

orbs:
  nais: navikt/nais-deployment@1.1.1
  docker: circleci/docker@0.5.1

executors:
  java:
     docker:
       - image: circleci/openjdk:11-jdk
  deployment:
    docker:
      - image: androa/ci-cd-toolbox

jobs:

  build-and-push:
    executor: java
    steps:
      - checkout
      - run:
          name: Lint, test, and build application
          command: ./scripts/build || ./gradlew build || npm build || true
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1

  prepare-nais:
    executor: deployment
    steps:
      - checkout
      - run:
          name: Set up necessary environment variables for deployment
          command: |
            echo "GITHUB_APP_ID=21626" >> ./nais/deploy.env
            echo "TEAM_NAME=$(yq r ./nais/base/kustomization.yaml commonLabels.team)" >> ./nais/deploy.env
            echo "APP_NAME=$(yq r ./nais/base/kustomization.yaml commonLabels.app)" >> ./nais/deploy.env
            echo "ZONE=$(yq r ./nais/base/kustomization.yaml commonAnnotations.zone)" >> ./nais/deploy.env

      - run:
          name: "Set image on base overlay"
          command: yq w -i nais/base/nais.yaml spec.image docker.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

      - run:
          name: "Prepare kustomized service contracts"
          command: |
            kustomize build ./nais/dev | tee ./nais/nais-dev-deploy.yaml
            kustomize build ./nais/prod | tee ./nais/nais-prod-deploy.yaml

      - persist_to_workspace:
          root: ./nais
          paths:
            - ./*deploy.yaml
            - deploy.env
            - deployment-request.json

  make-github-token:
    executor: deployment
    steps:
      - run:
          name: Inject GitHub App token
          command: curl -v https://github-circle-token-generator.herokuapp.com/token/inject?owner=$CIRCLE_PROJECT_USERNAME\&project=$CIRCLE_PROJECT_REPONAME

  create-github-deployment:
    executor: deployment
    steps:
      - attach_workspace:
          at: /tmp/nais

      - run:
          name: Load environment variables for deploy
          command: cat /tmp/nais/deploy.env >> $BASH_ENV

      - run:
          name: Create new deployment in the GitHub API
          command: |
            source /tmp/nais/deploy.env # Fix with custom image
            export YAML=$(yq r -j /tmp/nais/nais-dev-deploy.yaml)
            cat /tmp/nais/deployment-request.json | \
              jq ".environment = \"dev-${ZONE}\" | \
                  .description = \"Automated deploy to dev-${ZONE}\" | \
                  .payload.team = \"${TEAM_NAME}\" | \
                  .payload.kubernetes.resources = \"${YAML//\"/\\\"}\"" > deployment-request-dev.json

            curl -v \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "Accept: application/vnd.github.flash-preview+json" \
              -X POST \
              -d @deployment-request-dev.json \
              https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/deployments

      - persist_to_workspace:
          root: ./
          paths:
            - deployment-request-*.json

  acceptance-test-uat:
    executor: deployment
    steps:
      - run: ./scripts/test/uat || true

  acceptance-test-integration:
    executor: deployment
    steps:
      - run: ./scripts/test/integration || true

  acceptance-test-benchmark:
    executor: deployment
    steps:
      - run: ./scripts/test/benchmark || true

  deploy-preprod:
    executor: deployment
    steps:
      - attach_workspace:
          at: /tmp/nais
      - run: cat /tmp/nais/deploy.env >> $BASH_ENV
      - nais/generate-nais-deployment:
          nais-template: /tmp/nais/nais-dev-deploy.yaml
          github-app-id: $GITHUB_APP_ID
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          environment: dev-$ZONE
          repo: navikt/CIRCLE_PROJECT_REPONAME
          team: $TEAM_NAME

  deploy-prod:
    executor: deployment
    steps:
      - nais/generate-nais-deployment:
          nais-template: /tmp/nais/nais-prod-deploy.yaml
          github-app-id: $GITHUB_APP_ID
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          environment: prod-$ZONE
          repo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          team: $TEAM_NAME

workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build-and-push
      - prepare-nais
      - make-github-token:
          requires:
            - build-and-push
      - create-github-deployment:
      #- deploy-preprod:
          context: my-context
          requires:
            - build-and-push
            - prepare-nais
            - make-github-token
              #- acceptance-test-uat:
              #    requires:
              #      - deploy-preprod
              #- acceptance-test-integration:
              #    requires:
              #      - deploy-preprod
              #- acceptance-test-benchmark:
              #    requires:
              #      - deploy-preprod

              #- deploy-prod:
              #    requires:
              #      - acceptance-test-uat
              #      - acceptance-test-integration
              #      - acceptance-test-benchmark
              #    filters:
              #      branches:
              #        only: master
