version: 2.1

executors:
  builder_java:
    docker:
      - image: openjdk:11-jdk-slim

jobs:
  build_jar:
    executor: builder_java
    steps:
      - checkout
      - run: ./gradlew build

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build_jar
