version: 2.1

orbs:
  nais: navikt/nais-deployment@1.1.1
  docker: circleci/docker@0.5.1

executors:
  java:
     docker:
       - image: circleci/openjdk:11-jdk
  deployment:
    docker:
      - image: navikt/deployment-cli
  kustomize:
    docker:
      - image: bitlayer/kustomize@sha256:ab559c7a492656e0260680f89b71cdf07ee79e190020354563e0fdd5f986ac00

jobs:
  make-github-token:
    executor: java
    steps:
      - run:
          name: Inject GitHub App token
          command: curl -v https://github-circle-token-generator.herokuapp.com/token/inject?owner=$CIRCLE_PROJECT_USERNAME&project=$CIRCLE_PROJECT_REPONAME
  verify-github-token:
    executor: java
    steps:
    - run:
          name: Verify that token works
          command: |
            curl -i \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "Accept: application/vnd.github.machine-man-preview+json" \
              https://api.github.com/app

  build-and-push:
    executor: java
    steps:
      - checkout
      - run:
          name: Lint, test, and build application
          command: ./scripts/build || mvn build || npm build || true
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1

  prepare-nais:
    executor: kustomize
    steps:
      - checkout
      - run:
          name: Install root certificates
          command: apk --no-cache add ca-certificates curl
      - run:
          name: Install yq
          command: |
            curl -fLSs https://github.com/mikefarah/yq/releases/download/2.4.0/yq_linux_amd64 > /usr/local/bin/yq
            chmod +x /usr/local/bin/yq
      - run:
          name: Set up necessary environment variables for deployment
          command: |
            echo "export GITHUB_APP_ID=21626" >> ./nais/deploy.env
            echo "export TEAM_NAME=$(yq r nais/base/kustomization.yaml commonLabels.team)" >> ./nais/deploy.env
            echo "export APP_NAME=$(yq r nais/base/kustomization.yaml commonLabels.app)" >> ./nais/deploy.env
            echo "export ZONE=$(yq r nais/base/kustomization.yaml commonAnnotations.zone)" >> ./nais/deploy.env
      - run:
          name: "Set image on base overlay"
          command: yq w -i nais/base/nais.yaml spec.image docker.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - run:
          name: "Prepare kustomized service contracts"
          command: |
            kustomize build ./nais/dev | tee ./nais/nais-dev-deploy.yaml
            kustomize build ./nais/prod | tee ./nais/nais-prod-deploy.yaml
      - run:
          name: "Prepare GitHub deployment requests"
          command: |
            export YAML=$(yq r -j ./nais/nais-dev-deploy.yaml)
            cat ./nais/deployment-request.json | jq ".environment = \"dev-$ZONE\"|.payload.team = \"$TEAM_NAME\"|.payload.kubernetes.resources = \"${YAML//\"/\\\"}\"" > ./nais/deployment-request-dev.json
            export YAML=$(yq r -j ./nais/nais-prod-deploy.yaml)
            cat ./nais/deployment-request.json | jq ".environment = \"prod-$ZONE\"|.payload.team = \"$TEAM_NAME\"|.payload.kubernetes.resources = \"${YAML//\"/\\\"}\"" > ./nais/deployment-request-prod.json
      - persist_to_workspace:
          root: ./nais
          paths:
            - ./*deploy.yaml
            - deploy.env
            - deployment-request-*.json

  create-github-deployment:
    executor: deployment
    steps:
      - run:
          name: Create new deployment in the GitHub API
          command: |
            curl -i \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "Accept: application/vnd.github.machine-man-preview+json" \
              -X POST \
              -d @/tmp/nais/deployment-request-dev.json
              https://api.github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/deployments

  acceptance-test-uat:
    executor: kustomize
    steps:
      - run: ./scripts/test/uat || true

  acceptance-test-integration:
    executor: kustomize
    steps:
      - run: ./scripts/test/integration || true

  acceptance-test-benchmark:
    executor: kustomize
    steps:
      - run: ./scripts/test/benchmark || true

  deploy-preprod:
    executor: deployment
    steps:
      - attach_workspace:
          at: /tmp/nais
      - run: cat /tmp/nais/deploy.env >> $BASH_ENV
      - nais/generate-nais-deployment:
          nais-template: /tmp/nais/nais-dev-deploy.yaml
          github-app-id: $GITHUB_APP_ID
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          environment: dev-$ZONE
          repo: navikt/CIRCLE_PROJECT_REPONAME
          team: $TEAM_NAME

  deploy-prod:
    executor: deployment
    steps:
      - nais/generate-nais-deployment:
          nais-template: /tmp/nais/nais-prod-deploy.yaml
          github-app-id: $GITHUB_APP_ID
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          environment: prod-$ZONE
          repo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          team: $TEAM_NAME

workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build-and-push
      - prepare-nais
      - make-github-token
      - verify-github-token:
          requires:
            - make-github-token
      - create-github-deployment:
      #- deploy-preprod:
          context: my-context
          requires:
            - build-and-push
            - prepare-nais
            - make-github-token
              #- acceptance-test-uat:
              #    requires:
              #      - deploy-preprod
              #- acceptance-test-integration:
              #    requires:
              #      - deploy-preprod
              #- acceptance-test-benchmark:
              #    requires:
              #      - deploy-preprod

              #- deploy-prod:
              #    requires:
              #      - acceptance-test-uat
              #      - acceptance-test-integration
              #      - acceptance-test-benchmark
              #    filters:
              #      branches:
              #        only: master
