version: 2.1

executors:
  builder-java:
     docker:
       - image: circleci/openjdk:11-jdk

  toolbox:
    docker:
      - image: alpine:latest

jobs:
  build:
    executor: builder-java
    steps:
      - checkout
      - run: echo true
      - run: docker build .
      - run: echo true

  deploy-preprod:
    executor: toolbox
    environment:
      FOO: bar
    steps:
      - run: echo true

  acceptance-test-uat:
    executor: toolbox
    steps:
      - run: echo true

  acceptance-test-integration:
    executor: toolbox
    steps:
      - run: echo true

  acceptance-test-benchmark:
    executor: toolbox
    steps:
      - run: echo true

  deploy:
    executor: toolbox
    environment:
      FOO: bar
    steps:
      - run: kubectl

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy-preprod:
          filters:
            branches:
              only: master
      - acceptance-test-uat:
          requires:
            - deploy-preprod
      - acceptance-test-integration:
          requires:
            - deploy-preprod
      - acceptance-test-benchmark:
          requires:
            - deploy-preprod
      - deploy:
          requires:
            - prepare-nais
            - acceptance-test-uat
            - acceptance-test-integration
            - acceptance-test-benchmark
          filters:
            branches:
              only: master
