version: 2.1

orbs:
  nais: 'navikt/nais-deployment@1.1.1'

executors:
  java:
     docker:
       - image: circleci/openjdk:11-jdk

  toolbox:
    docker:
      - image: alpine:latest

  deployment:
    docker:
      - image: navikt/deployment-cli

jobs:
  build:
    executor: java
    steps:
      - checkout
      - run: echo "run some kind of build tool"
      - persist_to_workspace:
          root: .
          paths:
            - ./nais/*

  prepare-nais:
    executor: toolbox
    working_directory: /tmp/nais
    steps:
      - attach_workspace:
          at: /tmp/nais
      - run: pwd
      - run: ls .
      - run: ls /tmp
      - run: ls /tmp/nais
      - run:
          name: "Set image version on base overlay"
          command: sed -i 's/latest/${CIRCLE_SHA1}/' ./nais/base/nais.yaml
      - run:
          name: "Prepare dev service contract"
          command: kustomize build ./nais/dev -o ./nais/nais-dev-deploy.yaml && cat ./nais/nais-dev-deploy.yaml
      - run:
          name: "Prepare prod service contract"
          command: kustomize build ./nais/prod -o ./nais/nais-prod-deploy.yaml &&  cat ./nais/nais-prod-deploy.yaml
      - persist_to_workspace:
          root: .
          paths:
            - ./nais/*deploy.yaml

  acceptance-test-uat:
    executor: toolbox
    steps:
      - run: echo true

  acceptance-test-integration:
    executor: toolbox
    steps:
      - run: echo true

  acceptance-test-benchmark:
    executor: toolbox
    steps:
      - run: echo true

  publish-docker-image:
    executor: deployment
    steps:
      - nais/docker-deploy:
          image: $CIRCLE_PROJECT_REPONAME

  deploy-preprod:
    executor: deployment
    steps:
      - nais/generate-nais-deployment:
          nais-template: nais.yaml
          github-app-id: 1337
          image: $CIRCLE_PROJECT_REPONAME
          environment: dev-fss
          repo: navikt/example-repo
          team: awesome-team

  deploy-prod:
    executor: deployment
    steps:
      - nais/generate-nais-deployment:
          nais-template: nais.yaml
          github-app-id: 1337
          image: navikt/example-image
          environment: dev-fss
          repo: navikt/example-repo
          team: awesome-team

workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build
      - prepare-nais:
          requires:
            - build
      - publish-docker-image:
          requires:
            - build
      - deploy-preprod:
          requires:
            - publish-docker-image
      - acceptance-test-uat:
          requires:
            - deploy-preprod
      - acceptance-test-integration:
          requires:
            - deploy-preprod
      - acceptance-test-benchmark:
          requires:
            - deploy-preprod
      - deploy-prod:
          requires:
            - acceptance-test-uat
            - acceptance-test-integration
            - acceptance-test-benchmark
          filters:
            branches:
              only: master
