version: 2.1

orbs:
  nais: 'navikt/nais-deployment:1.1.1'

executors:
  builder-java:
     docker:
       - image: circleci/openjdk:11-jdk

  toolbox:
    docker:
      - image: alpine:latest

jobs:
  build:
    executor: builder-java
    steps:
      - checkout
      - run: echo "run some kind of build tool"

  prepare-nais:
    steps:
      - name: "Set image version on base overlay"
        command: sed -i 's/latest/${VERSION}/' ./nais/base/nais.yaml
      - name: "Prepare dev service contract"
        command: kustomize build ./nais/dev -o ./nais/nais-dev-deploy.yaml && cat ./nais/nais-dev-deploy.yaml
      - name: "Prepare prod service contract"
        command: kustomize build ./nais/prod -o ./nais/nais-prod-deploy.yaml &&  cat ./nais/nais-prod-deploy.yaml

  acceptance-test-uat:
    executor: toolbox
    steps:
      - run: echo true

  acceptance-test-integration:
    executor: toolbox
    steps:
      - run: echo true

  acceptance-test-benchmark:
    executor: toolbox
    steps:
      - run: echo true

  publish-docker-image:
    steps:
      - nais/docker-deploy:
          image: navikt/foo

  deploy-preprod:
    steps:
      - nais/deploy:
          build-and-push-docker-image: false
          repo: navikt/example-repo
          image: navikt/example-image
          github-app-id: 1337
          nais-template: nais.yaml
          environment: dev-fss
          team: awesome-team

  deploy-prod:
    steps:
      - nais/deploy:
          build-and-push-docker-image: false
          repo: navikt/example-repo
          image: navikt/example-image
          github-app-id: 1337
          nais-template: nais.yaml
          environment: prod-fss
          team: awesome-team

workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build
      - prepare-nais
      - publish-docker-image:
          requires:
            - build
            - prepare-nais
      - deploy-preprod
      - acceptance-test-uat:
          requires:
            - deploy-preprod
      - acceptance-test-integration:
          requires:
            - deploy-preprod
      - acceptance-test-benchmark:
          requires:
            - deploy-preprod
      - deploy-prod:
          requires:
            - acceptance-test-uat
            - acceptance-test-integration
            - acceptance-test-benchmark
          filters:
            branches:
              only: master
