name: Deploy

on: status

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@master
      - name: Checkout event data
        run: ls
        #run: ls ${GITHUB_EVENT_PATH}
