name: Deploy

on: [status, check_run, check_suite]

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@master
      - name: Checkout event data
        run: ls ${GITHUB_EVENT_PATH}
